language: node_js
node_js:
  - '8'
deploy:
  provider: npm
  email: info@pascal-iske.de
  api_key:
    secure: YXdGGMmGNsiwKOb6QZ5q5O8i7SLjeGU2rM+hLF7AQXYCyLGezplpdMoFqyoX1KhEBdQzr2iIfC8p4T2y/zbc1SPvGy540aR4uF7+tkhH22Ts3t8BdLkdCHf10I4Jjg6lsed1NPQsdpNx0fe9fdRNpo2q0a1YipJrDxRyZpaQjL5wfDgSpw59C5XI3YIP/xa4CPC3xSH8rFkCwvBFscdz4ebYNue3KKX+ImR57KOb99bF6I8vTBKEJ/4Xw/xImzX1VkNscRanBIy27Sl+vVRVKmI7AFSVAAP9mGGPsoghP+vHegPbSxEnaWCHcVcKQzV0hXjPKXQbsp8zPr/zW4ObjIi2Texf4MMWN1ZkRkgAwUfm4Pm1L452+lj4uZ5hEJTv0LpI/De4eEnbwDWMwgAOwpserN6eGleMLxea12kjQl3jyXLMsipCeb1hcQLwV2b/yuEj9tDvbBOmBPAAVDvGALhUZbOSnbkK+nzmBNxbnhuN8nR2J3pymmapLIv7xl6z1KBCdIbJnF9+o18UNdB7SiNVFab13/W1d2gXMPYIsLwxFUhF4jCA67KbCQesodU5S+sEpC/cy0SUFfciranxU+TTho02aJvCFd6i2gaEKg7zZTQWIJHuLJa8cQn2luexnIwbbGm3aKcbrTKDnzkx1c1HX5r4UKzB0FHmvtJYm5A=
  skip_cleanup: true
  on:
    tags: true
